# Site
repository: banyoungkwan//curriculum-vitae
# favicon: images/favicon.ico

# Personal info
name: Youngkwan Ban
title: Doctor of Philosophy
email: yban3@illinois.edu
website: https://banyoungkwan.github.io

# Social links
twitter_username: _sheepelss
# github_username:  sproogen
# dribbble_username: jekyll
facebook_username: youngkwan.ban
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: youngkwan-ban-91202647
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Youngkwan Ban and I'm a Ph.D. candidate (post-defence) in Media and Communication at University of Illinois at Urbana-Champaign. 
  My research interest are: <mark>Mediatised memory</mark>, <mark>Cultural memory</mark> and <mark>Asian Cultural Studies</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my academic interests some of my other interests and hobbies are:
   - Ashtanga Yoga
   - Contemporary Classical Music
   - Books, except the things in the selves "self-development"
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
